### PR TITLE
Interactive todo list

### PR DESCRIPTION
**Pull request by HFG43**
Thanks for your previous feedback and sending your project as an example, for better understanding.
I have corrected as requested the edit method.
While editing, you will be able to see the original text to edit. also, I have added that in case you want to edit it and it's empty, it will load again the original content for better UX.

Please, consider the general situation that is happening to a lot of students with webhint Linters 

Hi there!🙌

I'm sending this PR for you to review my code. 
Thank you in advance for your feedback! 🐱‍👤🐱‍👤

**Please, take into consideration the situation with the webhint Linter, as it appears in GitHub Action as not passed, but is a general issue.**

For this feature, I have included the following:

- Change completed value upon change event✔
- Store this change in Local Store✔
- Added a Clear All completed function, that filtered items in the array remaining those that are incomplete✔
- Review Linters✔
- Update Readme file✔

### CODE REVIEW

**Review by zainsadaqat — COMMENTED** [review]
# ❌ ❌ ❌Invalid Code Review Request ❌ ❌ ❌
# Hello @HFG43 👋  

## Something went wrong 

### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for this reason:

- ### You have submitted a project, where one of the linter is failing and not passing. Please make sure all linters are passing and green. 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by HFG43** [comment]
@zainsadaqat Hi! Thanks for your feedback. Could you please review as it  was for example called by a previous code Reviewer in a project some hours ago? He said the following: "The review can be done with webhint error as mentioned in the chanel by the SCR". As it is a general situation and cases with this particular issue are being reviewed 🙌🙌

**Review by AdnanOlarmmi — CHANGES_REQUESTED** [review]
Hi @HFG43, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

You're Almost there, funny one eyed alien

## Highlights
- Followed the wireframe.
- Tasks are being added and removed successfully.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by brainconnect93 — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi @HFG43, 👋 👋  

Your project is complete! Great job for following the project requirement🥇 and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 




## Good Points 👍

- Add and Remove functionality works Perfectly
- Edit Task functionality works fine

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
